In [ ]:
import re
import time
import pandas as pd
from tqdm.notebook import tqdm
from openai import OpenAI
from pathlib import Path

In [ ]:
INPUT_FILE = Path("../data/goemotions.csv")
OUTPUT_DIR = Path("../results_prompts_llm")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_FILE = OUTPUT_DIR / "llm_emotion_results.csv"

print(f"Input : {INPUT_FILE}")
print(f"Output: {OUTPUT_FILE}")

In [ ]:
INPUT_FILES = [Path("../data/goemotions.csv")]
COLS_TO_DROP = [
    "id", "example_very_unclear", "author", "subreddit",
    "link_id", "parent_id", "created_utc", "rater_id",
]
MODELS = {
    "gpt-4o":           "openai/gpt-4o",
    "claude-sonnet":    "anthropic/claude-sonnet-4.5",
    "gemini-2.5-pro":   "google/gemini-2.5-pro",
    "grok-3":           "x-ai/grok-3",
}
SLEEP_BETWEEN_CALLS = 4  
MAX_ROWS = 20

In [ ]:
OPENROUTER_API_KEY = Path("../secrets/openrouter_key.txt").read_text().strip()
client = OpenAI(
    api_key=OPENROUTER_API_KEY,
    base_url="https://openrouter.ai/api/v1",
)

In [10]:
def load_and_prepare_data(input_files, cols_to_drop):
    frames = []
    for f in input_files:
        if Path(f).exists():
            frames.append(pd.read_csv(f, sep=",", header=0))
        else:
            print(f"File not found, skipping: {f}")
    if not frames:
        raise FileNotFoundError("No input files could be loaded.")
    df = pd.concat(frames, ignore_index=True)
    existing_drop = [c for c in cols_to_drop if c in df.columns]
    df = df.drop(columns=existing_drop).drop_duplicates()
    emotion_columns = [c for c in df.columns if c != "text"]
    df["emotions"] = df[emotion_columns].apply(
        lambda row: ", ".join(row.index[row == 1]), axis=1
    )
    df = df[["text", "emotions"]].reset_index(drop=True)
    print(f"Loaded {len(df):,} unique sentences across {len(emotion_columns)} emotion classes.")
    print(f"Emotions: {emotion_columns}")
    return df, emotion_columns

In [11]:
SYSTEM_PROMPT = (
    "You are an expert in emotion analysis. "
    "When given a sentence, you identify which emotions from a provided list "
    "are expressed in it. You always end your answer with a line that starts with "
    "'Emotions:' followed by a comma-separated list of the emotions you detected "
    "(use only names from the provided list, nothing else on that line)."
)

In [12]:
def build_user_prompt(sentence, emotion_list):
    emotions_str = ", ".join(emotion_list)
    return (
        f'Sentence: "{sentence}"\n\n'
        f"Choose one or more emotions expressed in the sentence from this list:\n"
        f"{emotions_str}\n\n"
        f"Explain your reasoning briefly, then end with:\n"
        f"Emotions: <comma-separated emotions from the list above>"
    )

In [13]:
def extract_emotions(reply, valid_emotions):
    match = re.search(r"(?i)emotions?\s*:\s*(.+)", reply)
    if match:
        candidates = [e.strip().lower() for e in match.group(1).split(",")]
        found = [e for e in valid_emotions if e.lower() in candidates]
        if found:
            return ", ".join(found)
    reply_lower = reply.lower()
    found = [e for e in valid_emotions if re.search(rf"\b{re.escape(e.lower())}\b", reply_lower)]
    return ", ".join(found) if found else "none_found"

In [14]:
def query_model(model_id, sentence, emotion_list, retries=3):
    for attempt in range(retries):
        try:
            response = client.chat.completions.create(
                model=model_id,
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user",   "content": build_user_prompt(sentence, emotion_list)},
                ],
                temperature=0.2,
                max_tokens=2000,
            )
            return response.choices[0].message.content.strip()
        except Exception as e:
            wait = 2 ** attempt
            print(f"Attempt {attempt+1}/{retries} failed ({e}). Retrying in {wait}s...")
            time.sleep(wait)
    return "ERROR: all retries failed"

print("All helpers defined.")

All helpers defined.

In [ ]:
df, emotion_columns = load_and_prepare_data(INPUT_FILES, COLS_TO_DROP)
if MAX_ROWS:
    df = df.head(MAX_ROWS)
    print(f"MAX_ROWS={MAX_ROWS} - using a subset for testing.")

Loaded 154,135 unique sentences across 28 emotion classes.
Emotions: ['admiration', 'amusement', 'anger', 'annoyance', 'approval', 'caring', 'confusion', 'curiosity', 'desire', 'disappointment', 'disapproval', 'disgust', 'embarrassment', 'excitement', 'fear', 'gratitude', 'grief', 'joy', 'love', 'nervousness', 'optimism', 'pride', 'realization', 'relief', 'remorse', 'sadness', 'surprise', 'neutral']
MAX_ROWS=20 - using a subset for testing.

In [16]:
df = df.drop(index=1)
df

                                                 text                 emotions
0                                     That game hurt.                  sadness
2      You do right, if you don't care then fuck 'em!                  neutral
3                                  Man I love reddit.                     love
4   [NAME] was nowhere near them, he was by the Fa...                  neutral
5   Right? Considering it’s such an important docu...                gratitude
6   He isn't as big, but he's still quite popular....              disapproval
7   That's crazy; I went to a super [RELIGION] hig...                amusement
8                                 that's adorable asf                amusement
9   "Sponge Blurb Pubs Quaw Haha GURR ha AAa!" fin...                amusement
10  I have, and now that you mention it, I think t...                  neutral
11  I wanted to downvote this, but it's not your f...           disappointment
12                              BUT IT'S HER TURN! /s                  neutral
13                                       That is odd.  disappointment, disgust
14                                  Build a wall? /jk                  neutral
15  I appreciate it, that's good to know. I hope I...    admiration, gratitude
16  One time my 1 stopped right in 91st, I was abl...                  neutral
17  Well then I’d say you have a pretty good chanc...              realization
18           Pretty much every Punjabi dude I've met.               admiration
19  For extra measure tape it right by your crotch...                annoyance

In [17]:
### Run the pipeline

if OUTPUT_FILE.exists():
    existing = pd.read_csv(OUTPUT_FILE)
    print(f"Resuming: {len(existing):,} rows already saved.")
else:
    existing = pd.DataFrame(columns=["model", "sentence", "answer_from_the_model", "emotion_found"])
    print("Starting fresh.")

new_rows = []

for model_label, model_id in MODELS.items():
    print(f"\n{'='*65}")
    print(f"Model: {model_label}  ({model_id})")
    print(f"{'='*65}")

    already_done = set(
        existing.loc[existing["model"] == model_label, "sentence"]
    ) if not existing.empty else set()

    sentences_to_run = df[~df["text"].isin(already_done)]
    print(f"{len(sentences_to_run):,} to process - {len(already_done):,} already done.\n")

    for _, row in tqdm(sentences_to_run.iterrows(), total=len(sentences_to_run), desc=model_label):
        sentence = row["text"]

        reply         = query_model(model_id, sentence, emotion_columns)
        emotion_found = extract_emotions(reply, emotion_columns)

        new_rows.append({
            "model":                 model_label,
            "sentence":              sentence,
            "answer_from_the_model": reply,
            "emotion_found":         emotion_found,
            "true_emotions":         row["emotions"],
        })

        print(f"\n{'─'*60}")
        print(f"Model    : {model_label}")
        print(f"Sentence : {sentence[:120]}{'...' if len(sentence) > 120 else ''}")
        print(f"Reply    : {reply[:300]}{'...' if len(reply) > 300 else ''}")
        print(f"Emotions : {emotion_found}")
        print(f"True     : {row['emotions']}")

        time.sleep(SLEEP_BETWEEN_CALLS)

    if new_rows:
        combined = pd.concat([existing, pd.DataFrame(new_rows)], ignore_index=True)
        combined.to_csv(OUTPUT_FILE, index=False)
        print(f"\nSaved {len(combined):,} total rows to {OUTPUT_FILE}")

print(f"\nPipeline complete! Results at: {OUTPUT_FILE}")

Starting fresh.

=================================================================
Model: gpt-4o  (openai/gpt-4o)
=================================================================
19 to process - 0 already done.

gpt-4o:   0%|          | 0/19 [00:00<?, ?it/s]

────────────────────────────────────────────────────────────
Model    : gpt-4o
Sentence : That game hurt.
Reply    : The sentence "That game hurt" suggests an emotional response to an event, likely indicating a negative experience. The word "hurt" implies emotional pain or discomfort, which aligns with feelings of disappointment or sadness. The context of a game suggests that the speaker might have had expectation...
Emotions : disappointment, sadness
True     : sadness

────────────────────────────────────────────────────────────
Model    : gpt-4o
Sentence : You do right, if you don't care then fuck 'em!
Reply    : The sentence expresses a strong sense of disapproval and possibly anger towards others, as indicated by the use of the phrase "fuck 'em." There is also a sense of approval or pride in the decision to not care about what others think, as suggested by the phrase "You do right." The language used conve...
Emotions : anger, disapproval, pride
True     : neutral

────────────────────────────────────────────────────────────
Model    : gpt-4o
Sentence : Man I love reddit.
Reply    : The sentence "Man I love reddit." expresses a positive sentiment towards Reddit. The use of the word "love" indicates a strong positive feeling, which aligns with the emotion of love. Additionally, the sentence conveys a sense of joy or happiness about Reddit, which can be associated with the emotio...
Emotions : joy, love
True     : love

────────────────────────────────────────────────────────────
Model    : gpt-4o
Sentence : [NAME] was nowhere near them, he was by the Falcon.
Reply    : The sentence "[NAME] was nowhere near them, he was by the Falcon." is a straightforward statement of fact and does not inherently convey any emotional content. There are no words or context clues that suggest an emotional response or state. Therefore, the sentence is best categorized as neutral.

Em...
Emotions : neutral
True     : neutral

────────────────────────────────────────────────────────────
Model    : gpt-4o
Sentence : Right? Considering it’s such an important document, I should know the damned thing backwards and forwards... thanks agai...
Reply    : The sentence expresses a sense of annoyance, as indicated by the phrase "I should know the damned thing backwards and forwards," which suggests frustration with oneself for not being more familiar with the document. Additionally, there is gratitude expressed through the phrase "thanks again for the ...
Emotions : annoyance, gratitude
True     : gratitude

────────────────────────────────────────────────────────────
Model    : gpt-4o
Sentence : He isn't as big, but he's still quite popular. I've heard the same thing about his content. Never watched him much.
Reply    : The sentence expresses a neutral observation about someone who is popular despite not being as big as others. The speaker mentions hearing about the person's content but hasn't watched much, which suggests a lack of strong emotional engagement. There is no indication of positive or negative emotions...
Emotions : neutral
True     : disapproval

────────────────────────────────────────────────────────────
Model    : gpt-4o
Sentence : That's crazy; I went to a super [RELIGION] high school and I think I can remember 2 girls the entire 4 years that became...
Reply    : The sentence expresses a sense of surprise, as indicated by the phrase "That's crazy," which often signals something unexpected or astonishing. Additionally, there is a hint of realization as the speaker reflects on their high school experience and the rarity of teen motherhood among their peers. Th...
Emotions : realization, surprise
True     : amusement

────────────────────────────────────────────────────────────
Model    : gpt-4o
Sentence : that's adorable asf
Reply    : The sentence "that's adorable asf" expresses a positive reaction towards something perceived as cute or endearing. The use of "adorable" suggests a feeling of affection or fondness, which aligns with the emotion of love. Additionally, the informal intensifier "asf" (as fuck) emphasizes the speaker's...
Emotions : joy, love
True     : amusement

────────────────────────────────────────────────────────────
Model    : gpt-4o
Sentence : "Sponge Blurb Pubs Quaw Haha GURR ha AAa!" finale is too real
Reply    : The sentence refers to a finale being "too real," which suggests a strong reaction to the content. The use of "Haha" and the playful, nonsensical words like "Quaw" and "GURR" imply a sense of amusement or humor. The phrase "too real" can also indicate a sense of realization or surprise about how rel...
Emotions : amusement, realization, surprise
True     : amusement

────────────────────────────────────────────────────────────
Model    : gpt-4o
Sentence : I have, and now that you mention it, I think that's what triggered my nostalgia.
Reply    : The sentence expresses a sense of nostalgia, which is often associated with a longing for the past or a sentimental reflection. While nostalgia itself is not on the list, it can be closely related to emotions such as realization, as the speaker acknowledges a trigger for their nostalgic feeling. Add...
Emotions : realization
True     : neutral

────────────────────────────────────────────────────────────
Model    : gpt-4o
Sentence : I wanted to downvote this, but it's not your fault homie.
Reply    : The sentence expresses a mix of emotions. The speaker initially indicates a negative reaction, suggesting a feeling of disappointment or disapproval with the situation, as they mention wanting to "downvote this." However, the phrase "but it's not your fault homie" introduces a sense of understanding...
Emotions : caring, disappointment, disapproval
True     : disappointment

────────────────────────────────────────────────────────────
Model    : gpt-4o
Sentence : BUT IT'S HER TURN! /s
Reply    : The sentence "BUT IT'S HER TURN! /s" is written in all caps, which often indicates shouting or strong emotion. However, the inclusion of "/s" at the end is a common internet convention to denote sarcasm. This suggests that the speaker is not genuinely angry or upset but is instead expressing a sarca...
Emotions : amusement, annoyance
True     : neutral

────────────────────────────────────────────────────────────
Model    : gpt-4o
Sentence : That is odd.
Reply    : The sentence "That is odd." suggests a reaction to something unexpected or unusual. This typically aligns with the emotion of surprise, as it indicates a deviation from what is considered normal or expected. There is no strong indication of any other specific emotion from the list provided.

Emotion...
Emotions : surprise
True     : disappointment, disgust

────────────────────────────────────────────────────────────
Model    : gpt-4o
Sentence : Build a wall? /jk
Reply    : The sentence "Build a wall? /jk" includes the abbreviation "/jk," which stands for "just kidding." This suggests that the speaker is not serious about the statement, indicating a playful or humorous tone. The use of "/jk" typically implies that the speaker is joking, which aligns with the emotion of...
Emotions : amusement
True     : neutral

────────────────────────────────────────────────────────────
Model    : gpt-4o
Sentence : I appreciate it, that's good to know. I hope I'll have to apply that knowledge one day
Reply    : The sentence expresses a sense of gratitude with the phrase "I appreciate it," indicating a feeling of thankfulness. Additionally, the phrase "that's good to know" suggests approval of the information received. The hope expressed in "I hope I'll have to apply that knowledge one day" indicates optimi...
Emotions : approval, gratitude, optimism
True     : admiration, gratitude

────────────────────────────────────────────────────────────
Model    : gpt-4o
Sentence : One time my 1 stopped right in 91st, I was able to get a good photo of the platform since they have some lights along it...
Reply    : The sentence describes a situation where the speaker's train stopped, allowing them to take a good photo of the platform. The tone of the sentence is neutral and factual, with no strong emotional language or expressions of feelings. The mention of taking a good photo suggests a mild positive experie...
Emotions : neutral
True     : neutral

────────────────────────────────────────────────────────────
Model    : gpt-4o
Sentence : Well then I’d say you have a pretty good chance if it’s any girl lol
Reply    : The sentence expresses a light-hearted and playful tone, indicated by the use of "lol" (laugh out loud), which suggests amusement. Additionally, the phrase "pretty good chance" implies a positive outlook, indicating optimism. There is no indication of negative emotions or strong feelings such as ang...
Emotions : amusement, optimism
True     : realization

────────────────────────────────────────────────────────────
Model    : gpt-4o
Sentence : Pretty much every Punjabi dude I've met.
Reply    : The sentence "Pretty much every Punjabi dude I've met" lacks context and emotional indicators that would suggest a specific emotion. It appears to be a neutral statement, as it does not contain any words or phrases that convey strong feelings or attitudes. Without additional context or qualifiers, i...
Emotions : neutral
True     : admiration

────────────────────────────────────────────────────────────
Model    : gpt-4o
Sentence : For extra measure tape it right by your crotch so she can't take it for sexual assault reasons
Reply    : The sentence suggests a precautionary measure to avoid accusations of sexual assault, which implies a sense of fear regarding potential false accusations. Additionally, the tone of the sentence could be interpreted as containing a hint of annoyance or disapproval towards the situation that necessita...
Emotions : annoyance, disapproval, disgust, fear
True     : annoyance

Saved 19 total rows to /content/drive/MyDrive/nlp_project/results_prompts3/llm_emotion_results.csv

=================================================================
Model: claude-sonnet  (anthropic/claude-sonnet-4.5)
=================================================================
19 to process - 0 already done.

claude-sonnet:   0%|          | 0/19 [00:00<?, ?it/s]

────────────────────────────────────────────────────────────
Model    : claude-sonnet
Sentence : That game hurt.
Reply    : The sentence "That game hurt" expresses emotional pain or distress about a game's outcome. Let me analyze the possible emotions:

**Reasoning:**
- The word "hurt" indicates emotional pain, suggesting negative feelings about the game
- This could reflect **disappointment** - the speaker is let down b...
Emotions : disappointment, grief, sadness
True     : sadness

────────────────────────────────────────────────────────────
Model    : claude-sonnet
Sentence : You do right, if you don't care then fuck 'em!
Reply    : Let me analyze the emotions in this sentence.

The sentence "You do right, if you don't care then fuck 'em!" contains:

1. **Approval** - "You do right" is explicitly approving of someone's action or attitude
2. **Disapproval** - The phrase "fuck 'em" expresses strong disapproval or dismissal of oth...
Emotions : anger, approval, disapproval
True     : neutral

────────────────────────────────────────────────────────────
Model    : claude-sonnet
Sentence : Man I love reddit.
Reply    : The sentence "Man I love reddit" expresses a strong positive feeling toward Reddit. The use of "love" directly indicates affection and enthusiasm for the platform. The informal exclamation "Man" at the beginning adds emphasis and suggests genuine excitement or joy about Reddit.

The primary emotions...
Emotions : excitement, joy, love
True     : love

────────────────────────────────────────────────────────────
Model    : claude-sonnet
Sentence : [NAME] was nowhere near them, he was by the Falcon.
Reply    : Let me analyze this sentence for emotional content.

The sentence "[NAME] was nowhere near them, he was by the Falcon" appears to be a factual statement clarifying someone's location. It's correcting a potential misunderstanding about where this person was positioned - they weren't near "them" but r...
Emotions : disapproval, neutral
True     : neutral

────────────────────────────────────────────────────────────
Model    : claude-sonnet
Sentence : Right? Considering it’s such an important document, I should know the damned thing backwards and forwards... thanks agai...
Reply    : Let me analyze the emotions expressed in this sentence.

The speaker expresses several emotions:

1. **Gratitude** - The phrase "thanks again for the help!" clearly shows appreciation and thankfulness toward someone who has helped them.

2. **Annoyance/Frustration** - The use of "damned" and the sel...
Emotions : annoyance, embarrassment, gratitude, realization
True     : gratitude

────────────────────────────────────────────────────────────
Model    : claude-sonnet
Sentence : He isn't as big, but he's still quite popular. I've heard the same thing about his content. Never watched him much.
Reply    : Let me analyze the emotions in this sentence.

The speaker is discussing someone (likely a content creator) and makes several observations:

1. "He isn't as big, but he's still quite popular" - This shows a mild form of **approval** and **admiration**, acknowledging the person's popularity despite n...
Emotions : approval, neutral
True     : disapproval

────────────────────────────────────────────────────────────
Model    : claude-sonnet
Sentence : That's crazy; I went to a super [RELIGION] high school and I think I can remember 2 girls the entire 4 years that became...
Reply    : Let me analyze the emotions expressed in this sentence.

The speaker begins with "That's crazy," which indicates **surprise** at something unexpected or contrary to what might be assumed. They're contrasting their personal experience at a religious high school with what seems to be a common stereoty...
Emotions : disapproval, realization, surprise
True     : amusement

────────────────────────────────────────────────────────────
Model    : claude-sonnet
Sentence : that's adorable asf
Reply    : The sentence "that's adorable asf" expresses a strong positive reaction to something cute or endearing. The word "adorable" clearly indicates affection and appreciation, while "asf" (as f***) is an intensifier showing the strength of this feeling.

The primary emotion here is **admiration** - the sp...
Emotions : admiration, amusement, joy
True     : amusement

────────────────────────────────────────────────────────────
Model    : claude-sonnet
Sentence : "Sponge Blurb Pubs Quaw Haha GURR ha AAa!" finale is too real
Reply    : Let me analyze this sentence for emotional content.

The sentence appears to be commenting on something (possibly a show, performance, or event) with a chaotic, nonsensical title or description ("Sponge Blurb Pubs Quaw Haha GURR ha AAa!"). The key phrase is "finale is too real."

The phrase "too rea...
Emotions : nervousness, realization, surprise
True     : amusement

────────────────────────────────────────────────────────────
Model    : claude-sonnet
Sentence : I have, and now that you mention it, I think that's what triggered my nostalgia.
Reply    : Let me analyze this sentence for emotional content.

The speaker is responding to someone who mentioned something that helped them understand their own feelings. Key emotional indicators:

1. **Realization** - "now that you mention it, I think that's what triggered" shows the speaker is having a mom...
Emotions : approval, realization
True     : neutral

────────────────────────────────────────────────────────────
Model    : claude-sonnet
Sentence : I wanted to downvote this, but it's not your fault homie.
Reply    : Let me analyze the emotions in this sentence.

The speaker says "I wanted to downvote this" - this indicates they had a negative reaction to something, suggesting **disapproval** or **annoyance** with the content.

However, they follow with "but it's not your fault homie" - the word "but" signals a ...
Emotions : annoyance, approval, caring
True     : disappointment

────────────────────────────────────────────────────────────
Model    : claude-sonnet
Sentence : BUT IT'S HER TURN! /s
Reply    : Let me analyze this sentence step by step.

The sentence "BUT IT'S HER TURN! /s" contains several key elements:

1. **Capital letters and exclamation mark**: These suggest strong emotion or emphasis
2. **"BUT"**: Indicates contradiction or objection
3. **"/s"**: This is internet slang for "sarcasm" ...
Emotions : amusement, annoyance, disapproval
True     : neutral

────────────────────────────────────────────────────────────
Model    : claude-sonnet
Sentence : That is odd.
Reply    : The sentence "That is odd" expresses a reaction to something unexpected or unusual.

The speaker is observing something that doesn't fit their expectations or seems strange. This primarily conveys:

1. **Surprise** - The person has encountered something unexpected or out of the ordinary
2. **Confus...
Emotions : confusion, surprise
True     : disappointment, disgust

────────────────────────────────────────────────────────────
Model    : claude-sonnet
Sentence : Build a wall? /jk
Reply    : The sentence "Build a wall? /jk" appears to reference a politically charged topic (likely the border wall debate), but the "/jk" (meaning "just kidding") indicates the speaker is not being serious.

The "/jk" marker suggests the person is making a joke or being playful about what could otherwise be...
Emotions : amusement
True     : neutral

────────────────────────────────────────────────────────────
Model    : claude-sonnet
Sentence : I appreciate it, that's good to know. I hope I'll have to apply that knowledge one day
Reply    : Let me analyze this sentence for emotions:

The speaker says "I appreciate it" - this directly expresses **gratitude** for information received.

"that's good to know" shows **approval** of the information shared.

"I hope I'll have to apply that knowledge one day" reveals **optimism** - the speaker...
Emotions : approval, desire, gratitude, optimism
True     : admiration, gratitude

────────────────────────────────────────────────────────────
Model    : claude-sonnet
Sentence : One time my 1 stopped right in 91st, I was able to get a good photo of the platform since they have some lights along it...
Reply    : Let me analyze the emotions expressed in this sentence.

The speaker describes a situation where their train (likely the "1" train) stopped at 91st Street station. Rather than expressing frustration about the unexpected stop, they focus on the positive aspect - being able to take a good photo of the...
Emotions : approval, neutral
True     : neutral

────────────────────────────────────────────────────────────
Model    : claude-sonnet
Sentence : Well then I’d say you have a pretty good chance if it’s any girl lol
Reply    : Let me analyze this sentence for emotional content.

The sentence "Well then I'd say you have a pretty good chance if it's any girl lol" contains several emotional indicators:

1. **Optimism** - The phrase "you have a pretty good chance" expresses a positive outlook about someone's prospects
2. **Am...
Emotions : amusement, approval, optimism
True     : realization

────────────────────────────────────────────────────────────
Model    : claude-sonnet
Sentence : Pretty much every Punjabi dude I've met.
Reply    : Let me analyze this sentence for emotional content.

The sentence "Pretty much every Punjabi dude I've met" is a fragment that appears to be making a generalization about a group of people. Without additional context about what follows or what trait is being discussed, the statement itself is relati...
Emotions : neutral
True     : admiration

────────────────────────────────────────────────────────────
Model    : claude-sonnet
Sentence : For extra measure tape it right by your crotch so she can't take it for sexual assault reasons
Reply    : This sentence discusses recording something near one's crotch to prevent false accusations of sexual assault. Let me analyze the emotions expressed:

The statement reveals several concerning attitudes:

1. **Disapproval** - There's an implicit negative judgment about women making sexual assault accu...
Emotions : annoyance, disapproval, disgust, fear
True     : annoyance

Saved 38 total rows to /content/drive/MyDrive/nlp_project/results_prompts3/llm_emotion_results.csv

=================================================================
Model: gemini-2.5-pro  (google/gemini-2.5-pro)
=================================================================
19 to process - 0 already done.

gemini-2.5-pro:   0%|          | 0/19 [00:00<?, ?it/s]

────────────────────────────────────────────────────────────
Model    : gemini-2.5-pro
Sentence : That game hurt.
Reply    : The word "hurt" in this context refers to emotional pain resulting from the outcome of the game. This strongly suggests the speaker is experiencing `disappointment` because the result was not what they had hoped for. This feeling of being let down and the emotional pain it caused can also be describ...
Emotions : anger, disappointment, sadness
True     : sadness

────────────────────────────────────────────────────────────
Model    : gemini-2.5-pro
Sentence : You do right, if you don't care then fuck 'em!
Reply    : This sentence expresses a complex mix of emotions directed at different parties.

The phrase "You do right" is a clear statement of validation and support for the person being addressed, which signifies **Approval**.

The second part, "...if you don't care then fuck 'em!", is an aggressive and conte...
Emotions : anger, approval, disapproval, disgust
True     : neutral

────────────────────────────────────────────────────────────
Model    : gemini-2.5-pro
Sentence : Man I love reddit.
Reply    : The speaker explicitly uses the word "love," making **love** the most direct and primary emotion expressed. This strong positive feeling also indicates **joy** and **admiration** for the platform. By stating they love it, they are also giving their clear **approval**.

Emotions: love, joy, admiratio...
Emotions : admiration, approval, joy, love
True     : love

────────────────────────────────────────────────────────────
Model    : gemini-2.5-pro
Sentence : [NAME] was nowhere near them, he was by the Falcon.
Reply    : This sentence is a statement of fact, clarifying a person's location. It lacks any emotionally charged language or indicators of a subjective feeling. The tone is objective and informational, simply stating where the person was and was not.

Emotions: neutral
Emotions : neutral
True     : neutral

────────────────────────────────────────────────────────────
Model    : gemini-2.5-pro
Sentence : Right? Considering it’s such an important document, I should know the damned thing backwards and forwards... thanks agai...
Reply    : The speaker expresses a few distinct emotions in this sentence. The phrase "I should know the damned thing backwards and forwards" shows self-directed frustration for not knowing something important, which points to **annoyance**. This moment of understanding their own knowledge gap is also a **real...
Emotions : annoyance, gratitude, realization
True     : gratitude

────────────────────────────────────────────────────────────
Model    : gemini-2.5-pro
Sentence : He isn't as big, but he's still quite popular. I've heard the same thing about his content. Never watched him much.
Reply    : The sentence is a series of observations and factual statements. The speaker notes someone's popularity, relays secondhand information about their content, and states their own lack of direct experience. The tone is detached and informational, lacking any strong positive or negative emotional charge...
Emotions : neutral
True     : disapproval

────────────────────────────────────────────────────────────
Model    : gemini-2.5-pro
Sentence : That's crazy; I went to a super [RELIGION] high school and I think I can remember 2 girls the entire 4 years that became...
Reply    : The speaker's use of the phrase "That's crazy" indicates a strong reaction to information that is unexpected or hard to believe, which points directly to **surprise**. The speaker then contrasts this information with their own personal experience, recalling a specific fact from their memory ("I thin...
Emotions : realization, surprise
True     : amusement

────────────────────────────────────────────────────────────
Model    : gemini-2.5-pro
Sentence : that's adorable asf
Reply    : The word "adorable" expresses a strong positive sentiment of delight and charm, which directly corresponds to **Joy** and **Admiration**. The slang intensifier "asf" ("as fuck") elevates this feeling to an overwhelming degree, suggesting a deep sense of affection that is best described as **Love**. ...
Emotions : admiration, excitement, joy, love
True     : amusement

────────────────────────────────────────────────────────────
Model    : gemini-2.5-pro
Sentence : "Sponge Blurb Pubs Quaw Haha GURR ha AAa!" finale is too real
Reply    : The sentence expresses a strong, positive reaction to a piece of media. The quoted nonsensical string, which includes "Haha," indicates the speaker finds the moment incredibly funny, pointing to **amusement**. The chaotic nature of the sounds ("GURR ha AAa!") suggests a high-energy scene, and the sp...
Emotions : admiration, amusement, excitement, joy
True     : amusement

────────────────────────────────────────────────────────────
Model    : gemini-2.5-pro
Sentence : I have, and now that you mention it, I think that's what triggered my nostalgia.
Reply    : The speaker is having a moment of dawning awareness. The phrase "now that you mention it, I think that's what triggered..." points directly to a cognitive process where the speaker connects a cause to an effect, which is the definition of realization. The overall tone is reflective and lacks strong ...
Emotions : realization, neutral
True     : neutral

────────────────────────────────────────────────────────────
Model    : gemini-2.5-pro
Sentence : I wanted to downvote this, but it's not your fault homie.
Reply    : The speaker expresses **disapproval** with the phrase "I wanted to downvote this," indicating a negative judgment of the content. This is followed by a **realization**, conveyed by "but it's not your fault," where the speaker understands the person they are addressing is not to blame. Finally, the u...
Emotions : caring, disapproval, realization
True     : disappointment

────────────────────────────────────────────────────────────
Model    : gemini-2.5-pro
Sentence : BUT IT'S HER TURN! /s
Reply    : The use of all-caps and an exclamation mark initially suggests anger or frustration. However, the inclusion of "/s" at the end is a tone indicator for sarcasm. This completely changes the meaning, indicating the speaker is mocking the sentiment. They are expressing the opposite of what the words lit...
Emotions : amusement, annoyance, disapproval
True     : neutral

────────────────────────────────────────────────────────────
Model    : gemini-2.5-pro
Sentence : That is odd.
Reply    : The statement "That is odd" is a reaction to something unexpected, strange, or not easily understood. This directly points to **surprise**, as the speaker is encountering something that deviates from their expectations. It also implies a degree of **confusion**, as the thing being observed doesn't m...
Emotions : confusion, curiosity, surprise
True     : disappointment, disgust

────────────────────────────────────────────────────────────
Model    : gemini-2.5-pro
Sentence : Build a wall? /jk
Reply    : The use of "/jk" (just kidding) immediately signals that the preceding statement is not meant to be taken seriously and is intended as a joke. This points to the emotion of **amusement**.

Furthermore, making a joke about a controversial political slogan like "Build a wall" is often a form of mocker...
Emotions : amusement, disapproval
True     : neutral

────────────────────────────────────────────────────────────
Model    : gemini-2.5-pro
Sentence : I appreciate it, that's good to know. I hope I'll have to apply that knowledge one day
Reply    : The speaker begins by explicitly stating "I appreciate it," which is a clear expression of **gratitude**. The follow-up, "that's good to know," indicates a positive reception and valuation of the information, which shows **approval**. Finally, the sentence "I hope I'll have to apply that knowledge o...
Emotions : approval, desire, gratitude, optimism
True     : admiration, gratitude

────────────────────────────────────────────────────────────
Model    : gemini-2.5-pro
Sentence : One time my 1 stopped right in 91st, I was able to get a good photo of the platform since they have some lights along it...
Reply    : The speaker recounts an event in a matter-of-fact way. The unexpected train stop is not framed as an annoyance but as a positive opportunity. The phrase "good photo" indicates a positive judgment and satisfaction with the outcome, which aligns with approval. However, the overall low emotional intens...
Emotions : approval, neutral
True     : neutral

────────────────────────────────────────────────────────────
Model    : gemini-2.5-pro
Sentence : Well then I’d say you have a pretty good chance if it’s any girl lol
Reply    : The speaker is expressing a positive outlook on someone's chances, which indicates **optimism**. The use of "lol" (laughing out loud) and the slightly teasing tone of the qualifier "if it's any girl" clearly show that the speaker finds the situation or their own comment funny, which is a sign of **a...
Emotions : amusement, approval, optimism
True     : realization

────────────────────────────────────────────────────────────
Model    : gemini-2.5-pro
Sentence : Pretty much every Punjabi dude I've met.
Reply    : This sentence is a statement of observation or generalization. By itself, it lacks any emotional language or context. It could be the beginning of a sentence that expresses admiration ("...has been incredibly kind") or annoyance ("...has been really loud"), but the fragment alone does not convey any...
Emotions : neutral
True     : admiration

────────────────────────────────────────────────────────────
Model    : gemini-2.5-pro
Sentence : For extra measure tape it right by your crotch so she can't take it for sexual assault reasons
Reply    : This sentence offers cynical and crude advice aimed at preempting a sexual assault accusation. The core motivation is a clear **fear** of being falsely accused. The nature of the advice and the topic itself express **disgust** and strong **disapproval** of the situation that would necessitate such a...
Emotions : amusement, disapproval, disgust, fear
True     : annoyance

Saved 57 total rows to /content/drive/MyDrive/nlp_project/results_prompts3/llm_emotion_results.csv

=================================================================
Model: grok-3  (x-ai/grok-3)
=================================================================
19 to process - 0 already done.

grok-3:   0%|          | 0/19 [00:00<?, ?it/s]

────────────────────────────────────────────────────────────
Model    : grok-3
Sentence : That game hurt.
Reply    : The sentence "That game hurt" suggests a negative emotional experience related to the game, likely indicating emotional pain or frustration. The word "hurt" typically conveys a sense of sadness or disappointment, as it implies being emotionally affected in a negative way, possibly due to a loss or a...
Emotions : disappointment, sadness
True     : sadness

────────────────────────────────────────────────────────────
Model    : grok-3
Sentence : You do right, if you don't care then fuck 'em!
Reply    : The sentence "You do right, if you don't care then fuck 'em!" conveys a strong, dismissive attitude toward others' opinions, combined with a sense of defiance or frustration. The use of the phrase "fuck 'em" suggests irritation or anger toward those who might oppose or judge the speaker's actions. A...
Emotions : anger, approval
True     : neutral

────────────────────────────────────────────────────────────
Model    : grok-3
Sentence : Man I love reddit.
Reply    : The sentence "Man I love reddit." expresses a strong positive sentiment towards Reddit, indicating a deep affection or attachment to the platform. The use of "love" clearly points to the emotion of love, and there is also an element of approval in the positive tone of the statement.

Emotions: love,...
Emotions : approval, love
True     : love

────────────────────────────────────────────────────────────
Model    : grok-3
Sentence : [NAME] was nowhere near them, he was by the Falcon.
Reply    : The sentence "[NAME] was nowhere near them, he was by the Falcon." does not explicitly convey strong emotional content. It appears to be a factual statement about someone's location. There are no clear indicators of feelings or emotional tone in the wording or context provided. Therefore, the emotio...
Emotions : neutral
True     : neutral

────────────────────────────────────────────────────────────
Model    : grok-3
Sentence : Right? Considering it’s such an important document, I should know the damned thing backwards and forwards... thanks agai...
Reply    : In the given sentence, the speaker expresses frustration or mild annoyance with themselves for not knowing an important document well enough, as indicated by the phrase "I should know the damned thing backwards and forwards." Additionally, there is a clear expression of appreciation for the help rec...
Emotions : annoyance, gratitude
True     : gratitude

────────────────────────────────────────────────────────────
Model    : grok-3
Sentence : He isn't as big, but he's still quite popular. I've heard the same thing about his content. Never watched him much.
Reply    : The sentence "He isn't as big, but he's still quite popular. I've heard the same thing about his content. Never watched him much." conveys a sense of indifference or lack of strong personal opinion about the subject. The speaker acknowledges the person's popularity and reputation but expresses no pe...
Emotions : neutral
True     : disapproval

────────────────────────────────────────────────────────────
Model    : grok-3
Sentence : That's crazy; I went to a super [RELIGION] high school and I think I can remember 2 girls the entire 4 years that became...
Reply    : In analyzing the sentence, "That's crazy; I went to a super [RELIGION] high school and I think I can remember 2 girls the entire 4 years that became teen moms," I detect a sense of surprise due to the use of the phrase "That's crazy," which often conveys astonishment or disbelief at an unexpected si...
Emotions : realization, surprise
True     : amusement

────────────────────────────────────────────────────────────
Model    : grok-3
Sentence : that's adorable asf
Reply    : The sentence "that's adorable asf" expresses a strong positive sentiment towards something or someone, likely indicating a sense of affection or delight. The use of "adorable" suggests feelings of fondness and appreciation, which aligns with admiration and love. The informal intensifier "asf" (as f*...
Emotions : admiration, love
True     : amusement

────────────────────────────────────────────────────────────
Model    : grok-3
Sentence : "Sponge Blurb Pubs Quaw Haha GURR ha AAa!" finale is too real
Reply    : The sentence ""Sponge Blurb Pubs Quaw Haha GURR ha AAa!" finale is too real" suggests a strong emotional reaction to the finale of something, likely a show or story. The use of expressive sounds like "Haha" and "GURR ha AAa!" indicates a mix of laughter or amusement alongside an intense or surprisin...
Emotions : amusement, realization, surprise
True     : amusement

────────────────────────────────────────────────────────────
Model    : grok-3
Sentence : I have, and now that you mention it, I think that's what triggered my nostalgia.
Reply    : In the sentence "I have, and now that you mention it, I think that's what triggered my nostalgia," the speaker reflects on a past experience or memory that evokes a sentimental longing for the past. The term "nostalgia" typically relates to a mix of emotions, often including sadness for something lo...
Emotions : sadness
True     : neutral

────────────────────────────────────────────────────────────
Model    : grok-3
Sentence : I wanted to downvote this, but it's not your fault homie.
Reply    : In the sentence "I wanted to downvote this, but it's not your fault homie," there is an initial inclination to express negativity or criticism through the desire to downvote, which suggests disapproval. However, the speaker refrains from doing so and acknowledges that the other person is not to blam...
Emotions : caring, disapproval
True     : disappointment

────────────────────────────────────────────────────────────
Model    : grok-3
Sentence : BUT IT'S HER TURN! /s
Reply    : The sentence "BUT IT'S HER TURN! /s" suggests a tone of frustration or irritation, likely due to the use of all caps which often indicates shouting or strong emotion, and the content implying someone is not getting their fair chance. The "/s" tag typically indicates sarcasm, which can be associated ...
Emotions : annoyance
True     : neutral

────────────────────────────────────────────────────────────
Model    : grok-3
Sentence : That is odd.
Reply    : The sentence "That is odd" suggests a sense of puzzlement or mild bewilderment about something unexpected or unusual. It doesn't carry a strong emotional tone but implies a state of questioning or not fully understanding the situation.

Emotions: confusion, curiosity
Emotions : confusion, curiosity
True     : disappointment, disgust

────────────────────────────────────────────────────────────
Model    : grok-3
Sentence : Build a wall? /jk
Reply    : The sentence "Build a wall? /jk" includes a question followed by "/jk," which typically stands for "just kidding." This indicates that the speaker is not serious about the suggestion or question, likely using it in a playful or humorous manner. The tone suggests a lighthearted intent rather than a g...
Emotions : amusement
True     : neutral

────────────────────────────────────────────────────────────
Model    : grok-3
Sentence : I appreciate it, that's good to know. I hope I'll have to apply that knowledge one day
Reply    : The sentence "I appreciate it, that's good to know. I hope I'll have to apply that knowledge one day" conveys a sense of thankfulness for the information received, as indicated by the phrase "I appreciate it." This suggests gratitude. Additionally, the statement "I hope I'll have to apply that knowl...
Emotions : gratitude, optimism
True     : admiration, gratitude

────────────────────────────────────────────────────────────
Model    : grok-3
Sentence : One time my 1 stopped right in 91st, I was able to get a good photo of the platform since they have some lights along it...
Reply    : The sentence describes a moment where the speaker was able to take a good photo of a platform due to the lighting. The tone suggests a positive experience and a sense of satisfaction or interest in the opportunity to capture the photo. There is no indication of strong emotional intensity, but there ...
Emotions : approval, excitement
True     : neutral

────────────────────────────────────────────────────────────
Model    : grok-3
Sentence : Well then I’d say you have a pretty good chance if it’s any girl lol
Reply    : The sentence "Well then I’d say you have a pretty good chance if it’s any girl lol" conveys a lighthearted and positive tone. The use of "lol" suggests a casual, humorous intent, and the phrase "pretty good chance" indicates a sense of encouragement or positive outlook. This aligns with amusement du...
Emotions : amusement, optimism
True     : realization

────────────────────────────────────────────────────────────
Model    : grok-3
Sentence : Pretty much every Punjabi dude I've met.
Reply    : The sentence "Pretty much every Punjabi dude I've met" lacks clear emotional context or tone. It appears to be a neutral statement or observation without explicit expression of feelings such as admiration, annoyance, or amusement. There are no words or phrases that directly indicate a specific emoti...
Emotions : neutral
True     : admiration

────────────────────────────────────────────────────────────
Model    : grok-3
Sentence : For extra measure tape it right by your crotch so she can't take it for sexual assault reasons
Reply    : The sentence suggests a precautionary or defensive action with a tone that could imply irritation or frustration about a potential misunderstanding or accusation. The use of "so she can't take it for sexual assault reasons" indicates a sense of annoyance or disapproval toward the situation or percei...
Emotions : annoyance, disapproval
True     : annoyance

Saved 76 total rows to /content/drive/MyDrive/nlp_project/results_prompts3/llm_emotion_results.csv

Pipeline complete! Results at: /content/drive/MyDrive/nlp_project/results_prompts3/llm_emotion_results.csv

In [18]:
### Check the result
results = pd.read_csv(OUTPUT_FILE)
print(f"Total rows: {len(results):,}")
print(f"\nRows per model:")
print(results["model"].value_counts().to_string())
print(f"\nMost common predicted emotions:")
print(results["emotion_found"].value_counts().head(15).to_string())
results.head(10)

Total rows: 76

Rows per model:
model
gpt-4o            19
claude-sonnet     19
gemini-2.5-pro    19
grok-3            19

Most common predicted emotions:
emotion_found
neutral                                  11
realization, surprise                     3
amusement                                 3
approval, neutral                         3
amusement, optimism                       2
disappointment, sadness                   2
joy, love                                 2
amusement, realization, surprise          2
annoyance, disapproval, disgust, fear     2
amusement, annoyance, disapproval         2
annoyance, gratitude                      2
approval, desire, gratitude, optimism     2
amusement, approval, optimism             2
caring, disappointment, disapproval       1
approval, gratitude, optimism             1

,model,sentence,answer_from_the_model,emotion_found,true_emotions
0,gpt-4o,That game hurt.,"The sentence ""That game hurt"" suggests an emot...","disappointment, sadness",sadness
1,gpt-4o,"You do right, if you don't care then fuck 'em!",The sentence expresses a strong sense of disap...,"anger, disapproval, pride",neutral
2,gpt-4o,Man I love reddit.,"The sentence ""Man I love reddit."" expresses a ...","joy, love",love
3,gpt-4o,"[NAME] was nowhere near them, he was by the Fa...","The sentence ""[NAME] was nowhere near them, he...",neutral,neutral
4,gpt-4o,Right? Considering it’s such an important docu...,"The sentence expresses a sense of annoyance, a...","annoyance, gratitude",gratitude
5,gpt-4o,"He isn't as big, but he's still quite popular....",The sentence expresses a neutral observation a...,neutral,disapproval
6,gpt-4o,That's crazy; I went to a super [RELIGION] hig...,"The sentence expresses a sense of surprise, as...","realization, surprise",amusement
7,gpt-4o,that's adorable asf,"The sentence ""that's adorable asf"" expresses a...","joy, love",amusement
8,gpt-4o,"""Sponge Blurb Pubs Quaw Haha GURR ha AAa!"" fin...","The sentence refers to a finale being ""too rea...","amusement, realization, surprise",amusement
9,gpt-4o,"I have, and now that you mention it, I think t...","The sentence expresses a sense of nostalgia, w...",realization,neutral